### ISSUE TITLE
Fisheye camera models

### ISSUE THREAD

**Issue by slovak194** [oliver-batchelor/multical#16]
Hi!

> Note that there are currently no fisheye camera models - feel free to add one!

I have a willingness to look into that. Will it only require modifications to [multical/camera.py](https://github.com/saulzar/multical/blob/master/multical/camera.py)?

Best regards,
Alex

**Comment by saulzar** [comment]
Hi Alex,

That would be great. Yes I think that is the way to go. Happy to help as
you go, I don't have any fisheye camera myself to test with.

Possibly I would create a different camera class which uses fisheye
functions from cv2.fisheye. Currently the Camera class covers several
OpenCV camera models because they all use the same functions (potentially
different flags and number of distortion parameters).

Cheers,
Oliver

**Comment by slovak194** [comment]
Hi, @oliver-batchelor!

Shall this issue be closed as the PR made by @decamargo10 was merged?

Best regards,
Alex

**Comment by oliver-batchelor** [comment]
> Hi, @oliver-batchelor!
> 
> Shall this issue be closed as the PR made by @decamargo10 was merged?
> 
> Best regards, Alex

Yep! Thanks
