### ISSUE TITLE
Problem with running visualization: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by decamargo10** [oliver-batchelor/multical#23]
Hello,
I did the calibration and everything seems to work fine. However I can't get the visualization to work. I installed multical[visualization] but when I run it, I get the following error:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```
I tried uninstalling and reinstalling all kind of packages but the error remains. Anybody who experienced something similar or who has an idea how I could fix this?
OS: Ubuntu 20.04.

Thank you in advance!

**Comment by decamargo10** [comment]
Cleaning up my env and reinstalling qt5 using:
sudo apt-get install qt5-default
fixed it for me.

**Comment by oliver-batchelor** [comment]
Hi Lionel,

What platform/environment are you using?

I've seen this one many times. It's related to conflicts between opencv and
qt,  (because opencv includes a version of qt for it's gui stuff) and is
usually really annoying to sort out! One way which usually works is to use
a separate environment (e.g. conda or virtualenv) which uses
python-opencv-headless (instead of python-opencv).

Oliver
